numero1 = int(input("Ingrese un número: "))
numero2 = int(input("Ingrese otro número: "))
print("La suma es: ", numero1 + numero2)
print("La diferencia es: ", numero1 - numero2)
print("El producto es: ", numero1 * numero2)
print("La división es ", numero1 / numero2)